package com.EduLink.EduLink.model.enums;

public enum Major {
    COMPUTER_SCIENCE,
    SOFTWARE_ENGINEERING,
    INFORMATION_TECHNOLOGY,
    ELECTRICAL_ENGINEERING,
    MECHANICAL_ENGINEERING,
    CIVIL_ENGINEERING,
    CHEMICAL_ENGINEERING,
    PHYSICS,
    MATHEMATICS,
    BIOLOGY,
    CHEMISTRY,
    ECONOMICS,
    BUSINESS_ADMINISTRATION,
    MANAGEMENT,
    MARKETING,
    PSYCHOLOGY,
    SOCIOLOGY,
    LAW,
    MEDICINE,
    NURSING,
    PHARMACY,
    ARCHITECTURE,
    ENVIRONMENTAL_SCIENCE
}